// Libellés lisibles pour `ActivityLog.action` — partagés entre /journal
// (vue globale, Super Admin) et la page de profil/activité par utilisateur
// (vue filtrée sur un seul compte), pour ne jamais diverger entre les deux.
export const ACTION_LABELS: Record<string, string> = {
  LOGIN: "Connexion",
  BOUTIQUE_CREATED: "Boutique créée",
  BOUTIQUE_UPDATED: "Boutique modifiée",
  BOUTIQUE_ACTIVATED: "Boutique activée",
  BOUTIQUE_DEACTIVATED: "Boutique désactivée",
  USER_CREATED: "Utilisateur créé",
  USER_UPDATED: "Utilisateur modifié",
  USER_ACTIVATED: "Utilisateur activé",
  USER_DEACTIVATED: "Utilisateur désactivé",
  SETTINGS_UPDATED: "Paramètres modifiés",
  SETTINGS_LOGO_UPDATED: "Logo mis à jour",
  PRODUCT_CREATED: "Produit créé",
  PRODUCT_UPDATED: "Produit modifié",
  PRODUCT_DELETED: "Produit supprimé",
  PRODUCT_IMAGE_UPDATED: "Photo de produit mise à jour",
  CATEGORY_CREATED: "Catégorie créée",
  CATEGORY_UPDATED: "Catégorie modifiée",
  CATEGORY_DELETED: "Catégorie supprimée",
  SUBCATEGORY_CREATED: "Sous-catégorie créée",
  SUBCATEGORY_UPDATED: "Sous-catégorie modifiée",
  SUBCATEGORY_DELETED: "Sous-catégorie supprimée",
  SALE_CREATED: "Vente enregistrée",
  SALE_RETURN_CREATED: "Retour de vente",
  SALE_EDIT_REQUESTED: "Correction de vente signalée",
  SALE_ITEM_EDITED: "Vente corrigée",
  CREDIT_REPAYMENT: "Remboursement de crédit",
  CUSTOMER_CREATED: "Client créé",
  CUSTOMER_UPDATED: "Client modifié",
  EXPENSE_CREATED: "Dépense enregistrée",
  SUPPLIER_CREATED: "Fournisseur créé",
  SUPPLIER_UPDATED: "Fournisseur modifié",
  SUPPLIER_PAYMENT: "Paiement fournisseur",
  PURCHASE_ORDER_CREATED: "Commande fournisseur créée",
  PURCHASE_ORDER_RECEIVED: "Réception de commande",
  PURCHASE_ORDER_CANCELLED: "Commande fournisseur annulée",
  PURCHASE_ORDER_DELETED: "Commande fournisseur supprimée",
  STOCK_INVENTAIRE: "Inventaire de stock",
  TRANSFER_CREATED: "Transfert créé",
  TRANSFER_VALIDATED: "Transfert validé",
  TRANSFER_CANCELLED: "Transfert annulé",
  RESTOCK_REQUESTED: "Réapprovisionnement demandé",
  RESTOCK_RESOLVED: "Réapprovisionnement traité",
  RESTOCK_REJECTED: "Réapprovisionnement refusé",
  FACTORY_RESET: "Réinitialisation complète",
};
